GET http://localhost:8000/api/movies
Accept: application/json

###
PUT http://localhost:8000/api/movies/1/
Content-Type: application/json

{
  "title" : "Titanic",
  "description": "Romantic Movie"
}

###

POST http://localhost:8000/api/movies/
Content-Type: application/json

{
  "title": "Avatar",
  "description": "Blue Guy Sci-Fi"
}

###

POST http://localhost:8000/api/movies/
Content-Type: application/json

{
  "title": "Avatar",
  "description": "Blue Guy Sci-Fi"
}

###

POST http://localhost:8000/api/movies/4/rate_movie/
Content-Type: application/json

{
  "stars": 5
}

###

GET http://localhost:8000/api/movies/
Authorization: Token 5584eb3416228a452fbda63269cd065f1f7b2764
//Accept: application/json

###

// Method to create users
POST http://localhost:8000/api/users/
Content-Type: application/json

{"username": "jenghis3", "password": "jenghis3"}

###
POST http://localhost:8000/auth/
Content-Type: application/json


{"username": "jenghis3", "password": "jenghis3"}

###

